package sh.repost.gradle;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** JDK-only executable fixture for exercising the real build-plugin protocol through TestKit. */
public final class FakeRepostSchemaEngine {
    private FakeRepostSchemaEngine() {
    }

    /** Executes the capabilities or generation protocol fixture. */
    public static void main(String[] arguments) throws Exception {
        if (arguments.length == 2 && "capabilities".equals(arguments[0]) && "--json".equals(arguments[1])) {
            System.out.print(
                "{\"protocolVersion\":1,\"engineVersion\":\"0.9.0\"," +
                    "\"runtimeVersion\":\"1.0.0\",\"descriptorVersion\":2}"
            );
            return;
        }
        if (arguments.length != 3 || !"generate".equals(arguments[0]) || !"--request".equals(arguments[1])) {
            System.exit(64);
            return;
        }
        String request = Files.readString(Path.of(arguments[2]), StandardCharsets.UTF_8);
        Path schemaPath = Path.of(stringField(request, "schemaPath", 0));
        String schema = Files.readString(schemaPath, StandardCharsets.UTF_8);
        if (schema.contains("ENGINE_CRASH")) {
            System.exit(17);
            return;
        }
        if (schema.contains("ENGINE_TIMEOUT")) {
            Thread.sleep(10_000L);
            return;
        }
        if (schema.contains("DUPLICATE_FQCN")) {
            diagnostic(schemaPath, "DUPLICATE_FQCN", "duplicate emitted JVM FQCN com.acme.Duplicate", 3, 19);
            return;
        }
        if (schema.contains("SOURCE_SPAN_ERROR")) {
            diagnostic(schemaPath, "SCHEMA_INVALID", "fixture schema is invalid", 7, 23);
            return;
        }
        if (schema.contains("requiresEnv") && !hasEnvironmentInput(request, "PUBLIC_VALUE")) {
            diagnostic(schemaPath, "MISSING_ENV", "generator requires declared environment input PUBLIC_VALUE", 5, 17);
            return;
        }

        List<Generator> generators = generators(request, schema);
        List<Result> results = new ArrayList<>();
        for (Generator generator : generators) {
            results.add(generate(generator, request));
        }
        response(results, "[]");
    }

    private static Result generate(Generator generator, String request) throws IOException {
        String extension = "javaSdk".equals(generator.name) ? ".java" : ".kt";
        String environment = environmentValue(request, "PUBLIC_VALUE");
        String source = "// Generated by fake Repost engine\n" +
            (environment == null ? "" : "// PUBLIC_VALUE=" + environment + "\n") +
            "package " + generator.packageName + ";\n" +
            ("javaSdk".equals(generator.name)
                ? "public final class " + generator.clientName + " {}\n"
                : "public class " + generator.clientName + "\n");
        String sourceName = generator.clientName + extension;
        String generatorId = generatorId(generator);
        Path packageRoot = generator.sourceOutput;
        for (String segment : generator.packageName.split("\\.")) {
            packageRoot = packageRoot.resolve(segment);
        }
        Path resourceRoot = generator.resourceOutput
            .resolve("META-INF/repost/generated-clients/v1")
            .resolve(generatorId);
        Files.createDirectories(packageRoot);
        Files.createDirectories(resourceRoot);
        Files.writeString(packageRoot.resolve(sourceName), source, StandardCharsets.UTF_8);

        String schemaHash = "sha256:" + "a".repeat(64);
        String client = clientManifest(generator, generatorId, schemaHash);
        Files.writeString(resourceRoot.resolve("client.json"), client, StandardCharsets.UTF_8);
        String sourceHash = treeHash(sourceName, source);
        String resourceHash = treeHash("client.json", client);
        Files.writeString(
            packageRoot.resolve(".repost-client.json"),
            marker(generator, generatorId, schemaHash, "source", sourceName, sourceHash),
            StandardCharsets.UTF_8
        );
        Files.writeString(
            resourceRoot.resolve(".repost-client.json"),
            marker(generator, generatorId, schemaHash, "registry", "client.json", resourceHash),
            StandardCharsets.UTF_8
        );
        Files.createDirectories(generator.sourceControl);
        Files.createDirectories(generator.resourceControl);
        Files.writeString(
            generator.sourceControl.resolve("invocations.log"),
            generator.name + "\n",
            StandardCharsets.UTF_8,
            StandardOpenOption.CREATE,
            StandardOpenOption.APPEND
        );
        return new Result(generator, generatorId, sourceHash, resourceHash);
    }

    private static List<Generator> generators(String request, String schema) {
        List<Generator> generators = new ArrayList<>();
        int offset = 0;
        while (true) {
            int start = request.indexOf("\"generatorName\":", offset);
            if (start < 0) {
                return generators;
            }
            String name = stringField(request, "generatorName", start);
            generators.add(new Generator(
                name,
                Path.of(stringField(request, "sourceOutputDirectory", start)),
                Path.of(stringField(request, "resourceOutputDirectory", start)),
                Path.of(stringField(request, "sourceControlDirectory", start)),
                Path.of(stringField(request, "resourceControlDirectory", start)),
                generatorField(schema, name, "packageName", "javaSdk".equals(name) ? "com.acme.java" : "com.acme.kotlin"),
                generatorField(schema, name, "clientName", "javaSdk".equals(name) ? "JavaClient" : "KotlinClient")
            ));
            offset = start + 1;
        }
    }

    private static String generatorField(
        String schema,
        String generator,
        String field,
        String fallback
    ) {
        Matcher block = Pattern.compile(
            "generator\\s+" + Pattern.quote(generator) + "\\s*\\{([^}]*)}",
            Pattern.DOTALL
        ).matcher(schema);
        if (!block.find()) {
            return fallback;
        }
        Matcher value = Pattern.compile(
            Pattern.quote(field) + "\\s*=\\s*\"([^\"]+)\""
        ).matcher(block.group(1));
        return value.find() ? value.group(1) : fallback;
    }

    private static String clientManifest(Generator generator, String id, String schemaHash) {
        String type = generator.packageName + "." + generator.clientName;
        return "{\n" +
            "  \"formatVersion\": 1,\n" +
            "  \"generatorId\": \"" + id + "\",\n" +
            "  \"language\": \"" + language(generator.name) + "\",\n" +
            "  \"packageName\": \"" + generator.packageName + "\",\n" +
            "  \"clientType\": \"" + type + "\",\n" +
            "  \"factoryType\": \"" + type + "Factory\",\n" +
            "  \"schemaHash\": \"" + schemaHash + "\",\n" +
            "  \"descriptorVersion\": 2,\n" +
            "  \"runtimeVersion\": \"1.0.0\"\n" +
            "}\n";
    }

    private static String marker(
        Generator generator,
        String id,
        String schemaHash,
        String kind,
        String file,
        String treeHash
    ) {
        return "{\n" +
            "  \"formatVersion\": 2,\n" +
            "  \"language\": \"" + language(generator.name) + "\",\n" +
            "  \"engineVersion\": \"0.9.0\",\n" +
            "  \"generator\": \"" + generator.name + "\",\n" +
            "  \"outputKind\": \"" + kind + "\",\n" +
            "  \"generatorId\": \"" + id + "\",\n" +
            "  \"packageName\": \"" + generator.packageName + "\",\n" +
            "  \"schemaHash\": \"" + schemaHash + "\",\n" +
            "  \"runtimeVersion\": \"1.0.0\",\n" +
            "  \"descriptorVersion\": 2,\n" +
            "  \"clientName\": \"" + generator.clientName + "\",\n" +
            "  \"regenerateCommand\": \"repost schema generate\",\n" +
            "  \"treeHash\": \"" + treeHash + "\",\n" +
            "  \"files\": [\n" +
            "    \"" + file + "\"\n" +
            "  ]\n" +
            "}\n";
    }

    private static void diagnostic(Path path, String code, String message, int start, int end) {
        String diagnostic = "[{\"severity\":\"ERROR\",\"code\":\"" + code +
            "\",\"message\":\"" + message + "\",\"source\":{\"path\":\"" +
            json(path.toAbsolutePath().normalize().toString()) + "\",\"startByte\":" + start +
            ",\"endByte\":" + end + "}}]";
        response(new ArrayList<>(), diagnostic);
    }

    private static void response(List<Result> results, String diagnostics) {
        StringBuilder output = new StringBuilder(
            "{\"protocolVersion\":1,\"engineVersion\":\"0.9.0\"," +
                "\"runtimeVersion\":\"1.0.0\",\"descriptorVersion\":2,\"generators\":["
        );
        for (int index = 0; index < results.size(); index++) {
            if (index != 0) {
                output.append(',');
            }
            Result result = results.get(index);
            output.append("{\"generatorName\":\"").append(result.generator.name)
                .append("\",\"generatorId\":\"").append(result.generatorId)
                .append("\",\"sourceRoot\":\"").append(json(result.generator.sourceOutput.toString()))
                .append("\",\"resourceRoot\":\"").append(json(result.generator.resourceOutput.toString()))
                .append("\",\"sourceTreeHash\":\"").append(result.sourceHash)
                .append("\",\"resourceTreeHash\":\"").append(result.resourceHash).append("\"}");
        }
        output.append("],\"diagnostics\":").append(diagnostics).append('}');
        System.out.print(output);
    }

    private static String generatorId(Generator generator) {
        MessageDigest digest = sha256();
        digest.update((generator.name + "\n" + generator.packageName + "\n" + generator.clientName)
            .getBytes(StandardCharsets.UTF_8));
        return hex(digest.digest()).substring(0, 16);
    }

    private static String treeHash(String name, String contents) {
        MessageDigest digest = sha256();
        hashPart(digest, name.getBytes(StandardCharsets.UTF_8));
        hashPart(digest, contents.getBytes(StandardCharsets.UTF_8));
        return "sha256:" + hex(digest.digest());
    }

    private static void hashPart(MessageDigest digest, byte[] value) {
        digest.update(ByteBuffer.allocate(8).putLong(value.length).array());
        digest.update(value);
    }

    private static MessageDigest sha256() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private static String hex(byte[] value) {
        StringBuilder output = new StringBuilder(value.length * 2);
        for (byte item : value) {
            output.append(String.format("%02x", item & 0xff));
        }
        return output.toString();
    }

    private static boolean hasEnvironmentInput(String request, String name) {
        int environment = request.indexOf("\"environmentInputs\":{");
        return environment >= 0 && request.indexOf("\"" + name + "\":", environment) >= 0;
    }

    private static String environmentValue(String request, String name) {
        int environment = request.indexOf("\"environmentInputs\":{");
        if (environment < 0 || request.indexOf("\"" + name + "\":", environment) < 0) {
            return null;
        }
        return stringField(request, name, environment);
    }

    private static String stringField(String json, String name, int offset) {
        String prefix = "\"" + name + "\":\"";
        int start = json.indexOf(prefix, offset);
        if (start < 0) {
            throw new IllegalArgumentException("missing fixture request field " + name);
        }
        StringBuilder value = new StringBuilder();
        for (int index = start + prefix.length(); index < json.length(); index++) {
            char current = json.charAt(index);
            if (current == '"') {
                return value.toString();
            }
            if (current != '\\') {
                value.append(current);
                continue;
            }
            char escaped = json.charAt(++index);
            switch (escaped) {
                case 'n': value.append('\n'); break;
                case 'r': value.append('\r'); break;
                case 't': value.append('\t'); break;
                case 'b': value.append('\b'); break;
                case 'f': value.append('\f'); break;
                default: value.append(escaped);
            }
        }
        throw new IllegalArgumentException("unterminated fixture request field " + name);
    }

    private static String json(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String language(String generatorName) {
        return "javaSdk".equals(generatorName) ? "java" : "kotlin";
    }

    private static final class Generator {
        private final String name;
        private final Path sourceOutput;
        private final Path resourceOutput;
        private final Path sourceControl;
        private final Path resourceControl;
        private final String packageName;
        private final String clientName;

        private Generator(
            String name,
            Path sourceOutput,
            Path resourceOutput,
            Path sourceControl,
            Path resourceControl,
            String packageName,
            String clientName
        ) {
            this.name = name;
            this.sourceOutput = sourceOutput;
            this.resourceOutput = resourceOutput;
            this.sourceControl = sourceControl;
            this.resourceControl = resourceControl;
            this.packageName = packageName;
            this.clientName = clientName;
        }
    }

    private static final class Result {
        private final Generator generator;
        private final String generatorId;
        private final String sourceHash;
        private final String resourceHash;

        private Result(Generator generator, String generatorId, String sourceHash, String resourceHash) {
            this.generator = generator;
            this.generatorId = generatorId;
            this.sourceHash = sourceHash;
            this.resourceHash = resourceHash;
        }
    }
}
