package sh.repost.gradle;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

final class RepostGradleFunctionalTest {
    @Test
    void preservesEngineOwnedBytesAndAddsOnlyExplicitAggregateGlue() throws Exception {
        Path root = temporaryRoot("entrypoint-parity");
        try {
            Path project = root.resolve("app");
            writeGeneratingProject(project, "");

            BuildResult result = runner(project).build();
            assertEquals(TaskOutcome.SUCCESS, result.task(":repostGenerate").getOutcome());

            Path javaSource = project.resolve(
                "build/generated/sources/repost/javaSdk/java/com/acme/custom/CustomClient.java"
            );
            assertEquals(
                "// Generated by fake Repost engine\n" +
                    "package com.acme.custom;\n" +
                    "public final class CustomClient {}\n",
                Files.readString(javaSource, StandardCharsets.UTF_8)
            );
            Path javaResources = project.resolve("build/generated/resources/repost/javaSdk");
            Path clientManifest;
            try (java.util.stream.Stream<Path> paths = Files.walk(javaResources)) {
                clientManifest = paths
                    .filter(path -> path.getFileName().toString().equals("client.json"))
                    .findFirst()
                    .orElseThrow();
            }
            String clientBytes = Files.readString(clientManifest, StandardCharsets.UTF_8);
            assertTrue(clientBytes.startsWith("{\n  \"formatVersion\": 1,\n"), clientBytes);
            assertTrue(clientBytes.contains("\"clientType\": \"com.acme.custom.CustomClient\""), clientBytes);
            assertTrue(clientBytes.endsWith("\n"), clientBytes);

            Path generated = project.resolve("build/generated");
            try (java.util.stream.Stream<Path> paths = Files.walk(generated)) {
                for (Path file : paths.filter(Files::isRegularFile)
                    .collect(java.util.stream.Collectors.toList())) {
                    String relative = generated.relativize(file).toString().replace('\\', '/');
                    boolean engineOwned = relative.startsWith("sources/repost/") ||
                        relative.startsWith("resources/repost/");
                    boolean ownershipMarker = relative.endsWith("/.repost-output-root.json");
                    boolean aggregateGlue = relative.startsWith("sources/repostRegistry/") ||
                        relative.startsWith("resources/repostRegistry/");
                    assertTrue(
                        engineOwned || ownershipMarker || aggregateGlue,
                        "Gradle added non-aggregate generated output " + relative
                    );
                }
            }
            assertTrue(Files.isDirectory(project.resolve("build/generated/sources/repostRegistry")));
            assertTrue(Files.isDirectory(project.resolve("build/generated/resources/repostRegistry")));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void compilesTheSelectedPairedKotlinConsumer() throws Exception {
        String kotlinVersion = GradleTestVersions.kotlinVersion();
        Assumptions.assumeTrue(kotlinVersion != null && !kotlinVersion.isBlank());
        Path root = temporaryRoot("kotlin-pair-λ");
        try {
            Path project = root.resolve("consumer");
            Files.createDirectories(project.resolve("repost"));
            Files.writeString(project.resolve("settings.gradle"), "rootProject.name = 'kotlin-pair'\n");
            Files.writeString(
                project.resolve("repost/schema.repost"),
                "generator javaSdk { packageName = \"com.acme.java\" clientName = \"JavaClient\" }\n" +
                    "generator kotlinSdk { packageName = \"com.acme.kotlin\" clientName = \"KotlinClient\" }\n"
            );
            String engine = writeEngine(project.resolve("fake-repost-engine"));
            Files.writeString(
                project.resolve("build.gradle"),
                "plugins { id 'org.jetbrains.kotlin.jvm' version '" + kotlinVersion + "'; id 'sh.repost.sdk' }\n" +
                    "repositories { mavenCentral() }\n" +
                    "group = 'com.acme'\n" +
                    "tasks.named('repostGenerate') { " +
                    "engineExecutable.set(layout.projectDirectory.file('" + engine + "')) }\n"
            );

            BuildResult result = GradleTestVersions.apply(GradleRunner.create()
                .withProjectDir(project.toFile())
                .withPluginClasspath()
                .withEnvironment(testEnvironment(project, Map.of()))
                .withArguments("--configuration-cache", "--stacktrace", "compileKotlin", "processResources"))
                .build();

            assertEquals(TaskOutcome.SUCCESS, result.task(":repostGenerate").getOutcome());
            assertEquals(TaskOutcome.SUCCESS, result.task(":compileKotlin").getOutcome());
            assertEquals(TaskOutcome.SUCCESS, result.task(":processResources").getOutcome());
            assertFalse(Files.exists(project.resolve("build/resources/main/.repost-output-root.json")));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void relocatedCacheRestoreContainsOnlyOwnedOutputsAndNoControlState() throws Exception {
        Path root = temporaryRoot("relocated-cache-λ");
        try {
            Path first = root.resolve("first");
            Path relocated = root.resolve("relocated");
            writeGeneratingProject(first, "");
            writeGeneratingProject(relocated, "");

            assertEquals(TaskOutcome.SUCCESS, runner(first).build().task(":repostGenerate").getOutcome());
            BuildResult restored = runner(relocated).build();

            assertEquals(TaskOutcome.FROM_CACHE, restored.task(":repostGenerate").getOutcome());
            assertTrue(Files.isRegularFile(relocated.resolve(
                "build/generated/sources/repost/javaSdk/java/com/acme/custom/CustomClient.java"
            )));
            assertTrue(containsNamed(relocated.resolve("build/generated"), ".repost-output-root.json"));
            assertFalse(Files.exists(relocated.resolve("build/.repost-sdk-state")));
            assertFalse(containsNamed(relocated.resolve("build/generated"), "invocations.log"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void aggregatesRegistriesFromTwoDependencyProjectsAndAnExternalJar() throws Exception {
        Path root = temporaryRoot("registries");
        try {
            Path project = root.resolve("app");
            Files.createDirectories(project.resolve("libs"));
            Files.writeString(
                project.resolve("settings.gradle"),
                "rootProject.name = 'registry-app'\n" +
                    "buildCache { local { directory = file('../build-cache') } }\n" +
                    "include 'one', 'two'\n"
            );
            Files.writeString(
                project.resolve("build.gradle"),
                "plugins { id 'java'; id 'sh.repost.sdk' }\n" +
                    "group = 'com.acme'\n" +
                    "dependencies { implementation project(':one'); implementation project(':two'); " +
                    "implementation files('libs/external.jar') }\n" +
                    "repostSdk.schemaMode.set(sh.repost.gradle.RepostSchemaMode.AGGREGATE_ONLY)\n"
            );
            writeRegistryProject(project.resolve("one"), "1111111111111111", "aaaaaaaaaaaaaaaa", "one");
            writeRegistryProject(project.resolve("two"), "2222222222222222", "bbbbbbbbbbbbbbbb", "two");
            registryJar(
                project.resolve("libs/external.jar"),
                "3333333333333333",
                "cccccccccccccccc",
                "external"
            );

            BuildResult result = runner(project).build();
            assertEquals(TaskOutcome.SUCCESS, result.task(":repostGenerate").getOutcome());
            String generated = generatedText(project);
            assertTrue(generated.contains("com.acme.one.OneClientFactory.INSTANCE"));
            assertTrue(generated.contains("com.acme.two.TwoClientFactory.INSTANCE"));
            assertTrue(generated.contains("com.acme.external.ExternalClientFactory.INSTANCE"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void reportsDuplicateRegistryArtifactsAndAmbiguousDeclaredIntegrations() throws Exception {
        Path root = temporaryRoot("registry-failures");
        try {
            Path duplicate = root.resolve("duplicate");
            Files.createDirectories(duplicate);
            Files.writeString(
                duplicate.resolve("settings.gradle"),
                "rootProject.name = 'duplicate-app'\ninclude 'one', 'two'\n"
            );
            Files.writeString(
                duplicate.resolve("build.gradle"),
                "plugins { id 'java'; id 'sh.repost.sdk' }\n" +
                    "dependencies { implementation project(':one'); implementation project(':two') }\n" +
                    "repostSdk.schemaMode.set(sh.repost.gradle.RepostSchemaMode.AGGREGATE_ONLY)\n"
            );
            writeRegistryProject(duplicate.resolve("one"), "1111111111111111", "aaaaaaaaaaaaaaaa", "one");
            writeRegistryProject(duplicate.resolve("two"), "2222222222222222", "aaaaaaaaaaaaaaaa", "two");
            String duplicateOutput = runner(duplicate).buildAndFail().getOutput();
            assertTrue(duplicateOutput.contains("duplicate Repost generator aaaaaaaaaaaaaaaa"));
            assertTrue(duplicateOutput.contains("project :one") || duplicateOutput.contains("project ':one'"));
            assertTrue(duplicateOutput.contains("project :two") || duplicateOutput.contains("project ':two'"));
            assertTrue(duplicateOutput.contains("one.jar"));
            assertTrue(duplicateOutput.contains("two.jar"));

            Path ambiguous = root.resolve("ambiguous");
            Files.createDirectories(ambiguous);
            Files.createDirectories(ambiguous.resolve("repost-client-spring-boot-starter"));
            Files.createDirectories(ambiguous.resolve("repost-client-cdi"));
            Files.writeString(
                ambiguous.resolve("settings.gradle"),
                "rootProject.name = 'ambiguous-app'\n" +
                    "include 'repost-client-spring-boot-starter', 'repost-client-cdi'\n"
            );
            Files.writeString(
                ambiguous.resolve("build.gradle"),
                "plugins { id 'java'; id 'sh.repost.sdk' }\n" +
                    "dependencies { implementation project(':repost-client-spring-boot-starter'); " +
                    "implementation project(':repost-client-cdi') }\n" +
                    "repostSdk.schemaMode.set(sh.repost.gradle.RepostSchemaMode.AGGREGATE_ONLY)\n" +
                    "subprojects { apply plugin: 'java'; group = 'sh.repost' }\n"
            );
            String ambiguity = runner(ambiguous).buildAndFail().getOutput();
            assertTrue(ambiguity.contains(
                "multiple declared Repost adapters require integration NONE, SPRING_BOOT, or CDI"
            ));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void generatesMultipleCustomClientsWithoutAnInstalledCliAndKeepsControlStateSeparate() throws Exception {
        Path root = temporaryRoot("custom");
        try {
            Path project = root.resolve("app");
            writeGeneratingProject(
                project,
                customBuild("build/custom/java-source") +
                    "repostSdk.generators.named('kotlinSdk') {\n" +
                    "    sourceOutputDirectory.set(layout.buildDirectory.dir('custom/kotlin-source'))\n" +
                    "    resourceOutputDirectory.set(layout.buildDirectory.dir('custom/kotlin-resources'))\n" +
                    "}\n"
            );

            BuildResult result = runner(project).build();

            assertEquals(TaskOutcome.SUCCESS, result.task(":repostGenerate").getOutcome());
            assertTrue(Files.isRegularFile(
                project.resolve("build/custom/java-source/com/acme/custom/CustomClient.java")
            ));
            assertTrue(Files.isRegularFile(
                project.resolve("build/custom/kotlin-source/com/acme/kotlin/KotlinClient.kt")
            ));
            assertTrue(Files.isRegularFile(project.resolve("build/custom/java-source/.repost-output-root.json")));
            assertTrue(Files.isRegularFile(project.resolve("build/custom/kotlin-resources/.repost-output-root.json")));
            assertFalse(containsNamed(project.resolve("build/custom"), "invocations.log"));
            assertTrue(containsNamed(project.resolve("build/.repost-sdk-state"), "invocations.log"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void onlyDeclaredEnvironmentInputsInvalidateCacheAndCacheRestoreExcludesControlState() throws Exception {
        Path root = temporaryRoot("environment-cache");
        try {
            Path project = root.resolve("app");
            writeGeneratingProject(
                project,
                "repostSdk.environmentInputs.put('PUBLIC_VALUE', " +
                    "providers.environmentVariable('DECLARED_REPOST_VALUE'))\n"
            );

            BuildResult initial = runner(project, Map.of(
                "DECLARED_REPOST_VALUE", "one",
                "AMBIENT_REPOST_VALUE", "ambient-one"
            )).build();
            assertEquals(TaskOutcome.SUCCESS, initial.task(":repostGenerate").getOutcome());
            assertTrue(initial.getOutput().contains("Configuration cache entry stored"));
            assertTrue(generatedText(project).contains("PUBLIC_VALUE=one"));

            deleteTree(project.resolve("build"));
            BuildResult ambientChange = runner(project, Map.of(
                "DECLARED_REPOST_VALUE", "one",
                "AMBIENT_REPOST_VALUE", "ambient-two"
            )).build();
            assertEquals(TaskOutcome.FROM_CACHE, ambientChange.task(":repostGenerate").getOutcome());
            assertTrue(ambientChange.getOutput().contains("Reusing configuration cache"));
            assertTrue(generatedText(project).contains("PUBLIC_VALUE=one"));
            assertFalse(Files.exists(project.resolve("build/.repost-sdk-state")));
            assertFalse(containsNamed(project.resolve("build/generated"), "invocations.log"));

            deleteTree(project.resolve("build"));
            BuildResult declaredChange = runner(project, Map.of(
                "DECLARED_REPOST_VALUE", "two",
                "AMBIENT_REPOST_VALUE", "ambient-two"
            )).build();
            assertEquals(TaskOutcome.SUCCESS, declaredChange.task(":repostGenerate").getOutcome());
            assertTrue(generatedText(project).contains("PUBLIC_VALUE=two"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void reportsExactSchemaSpansDuplicateFqcnsAndEngineFailures() throws Exception {
        Path root = temporaryRoot("failures");
        try {
            assertEngineFailure(root.resolve("span"), "SOURCE_SPAN_ERROR", "SCHEMA_INVALID", "7-23");
            assertEngineFailure(root.resolve("fqcn"), "DUPLICATE_FQCN", "DUPLICATE_FQCN", "3-19");
            assertEngineFailure(root.resolve("crash"), "ENGINE_CRASH", "schema engine exited unsuccessfully", null);

            Path timeout = root.resolve("timeout");
            writeGeneratingProject(
                timeout,
                "repostSdk.executionTimeout.set(java.time.Duration.ofMillis(200))\n"
            );
            Files.writeString(timeout.resolve("repost/schema.repost"), "ENGINE_TIMEOUT\n");
            assertTrue(runner(timeout).buildAndFail().getOutput().contains("schema engine execution timed out"));

            Path missingEnvironment = root.resolve("missing-environment");
            writeGeneratingProject(missingEnvironment, "");
            Files.writeString(missingEnvironment.resolve("repost/schema.repost"), "requiresEnv\n");
            BuildResult missing = runner(missingEnvironment).buildAndFail();
            assertTrue(missing.getOutput().contains("MISSING_ENV"));
            assertTrue(missing.getOutput().contains("5-17"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void followsSchemaRenameThenFailsWhenTheDeclaredSchemaIsDeleted() throws Exception {
        Path root = temporaryRoot("schema-rename");
        try {
            Path project = root.resolve("app");
            writeGeneratingProject(project, "repostSdk.schemaFile.set(layout.projectDirectory.file('repost/renamed.repost'))\n");
            Files.move(project.resolve("repost/schema.repost"), project.resolve("repost/renamed.repost"));
            assertEquals(TaskOutcome.SUCCESS, runner(project).build().task(":repostGenerate").getOutcome());

            Files.delete(project.resolve("repost/renamed.repost"));
            BuildResult deleted = runner(project).buildAndFail();
            assertTrue(deleted.getOutput().contains("renamed.repost"));
            assertTrue(deleted.getOutput().contains("doesn't exist") || deleted.getOutput().contains("does not exist"));
        } finally {
            deleteTree(root);
        }
    }

    @Test
    void rejectsUnmarkedAndSharedPrimaryOutputsBeforeLaunchingTheEngine() throws Exception {
        Path root = temporaryRoot("ownership");
        try {
            Path unmarked = root.resolve("unmarked");
            writeGeneratingProject(unmarked, customBuild("build/custom/java-source"));
            Path userFile = unmarked.resolve("build/custom/java-source/UserOwned.java");
            Files.createDirectories(userFile.getParent());
            Files.writeString(userFile, "user-owned\n", StandardCharsets.UTF_8);

            BuildResult unmarkedFailure = runner(unmarked).buildAndFail();
            assertTrue(unmarkedFailure.getOutput().contains(
                "Repost generated output root is non-empty and has no ownership marker"
            ));
            assertTrue(Files.readString(userFile).equals("user-owned\n"));

            Path shared = root.resolve("shared");
            writeGeneratingProject(shared, customBuild("src/main/java"));
            BuildResult sharedFailure = runner(shared).buildAndFail();
            assertTrue(sharedFailure.getOutput().contains(
                "Repost primary generated output must not use a shared src directory"
            ));
        } finally {
            deleteTree(root);
        }
    }

    private static String customBuild(String javaSourceOutput) {
        return "repostSdk {\n" +
            "    generators.named('javaSdk') {\n" +
            "        sourceOutputDirectory.set(layout.projectDirectory.dir('" + javaSourceOutput + "'))\n" +
            "        resourceOutputDirectory.set(layout.buildDirectory.dir('custom/java-resources'))\n" +
            "    }\n" +
            "}\n";
    }

    private static void writeGeneratingProject(Path project, String configuration) throws Exception {
        Files.createDirectories(project.resolve("repost"));
        Files.writeString(
            project.resolve("settings.gradle"),
            "rootProject.name = 'functional-fixture'\n" +
                "buildCache { local { directory = file('../build-cache') } }\n"
        );
        Files.writeString(
            project.resolve("repost/schema.repost"),
            "generator javaSdk { packageName = \"com.acme.custom\" clientName = \"CustomClient\" }\n" +
                "generator kotlinSdk { packageName = \"com.acme.kotlin\" clientName = \"KotlinClient\" }\n"
        );
        String engine = writeEngine(project.resolve("fake-repost-engine"));
        Files.writeString(
            project.resolve("build.gradle"),
            "plugins { id 'java'; id 'sh.repost.sdk' }\n" +
                "group = 'com.acme'\n" + configuration +
                "tasks.named('repostGenerate') { engineExecutable.set(layout.projectDirectory.file('" + engine + "')) }\n"
        );
    }

    private static String writeEngine(Path executable) throws IOException, URISyntaxException {
        Path classes = Path.of(FakeRepostSchemaEngine.class.getProtectionDomain()
            .getCodeSource().getLocation().toURI());
        boolean windows = System.getProperty("os.name").startsWith("Windows");
        String java = Path.of(
            System.getProperty("java.home"),
            "bin",
            windows ? "java.exe" : "java"
        ).toString();
        if (windows) {
            executable = executable.resolveSibling(executable.getFileName() + ".cmd");
        }
        Files.writeString(
            executable,
            windows
                ? "@echo off\r\nchcp 65001 >nul\r\nif \"%~1\"==\"capabilities\" goto capabilities\r\n" +
                    "cd /d \"%~dp0\"\r\n" +
                    "for %%F in (\"build\\.repost-sdk-state\\generate\\requests\\.repost-generation-*.json\") do \"" + java +
                    "\" -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8" +
                    " -Xms16m -Xmx128m -XX:+UseSerialGC" +
                    " -XX:ActiveProcessorCount=2 -cp \"" + classes +
                    "\" sh.repost.gradle.FakeRepostSchemaEngine %1 %2 \"%%~F\"\r\n" +
                    "exit /b %errorlevel%\r\n" +
                    ":capabilities\r\n\"" + java +
                    "\" -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8" +
                    " -Xms16m -Xmx128m -XX:+UseSerialGC" +
                    " -XX:ActiveProcessorCount=2 -cp \"" + classes +
                    "\" sh.repost.gradle.FakeRepostSchemaEngine %1 %2\r\n"
                : "#!/bin/sh\n" +
                    "if locale -a 2>/dev/null | grep -Eiq '^C\\.utf-?8$'; then export LC_ALL=C.UTF-8; fi\n" +
                    "exec " + shell(java) +
                    " -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8" +
                    " -Xms16m -Xmx128m -XX:+UseSerialGC -XX:ActiveProcessorCount=2 -cp " +
                    shell(classes.toString()) + " sh.repost.gradle.FakeRepostSchemaEngine \"$@\"\n",
            StandardCharsets.UTF_8
        );
        if (!windows) {
            try {
                Files.setPosixFilePermissions(executable, EnumSet.of(
                    PosixFilePermission.OWNER_READ,
                    PosixFilePermission.OWNER_WRITE,
                    PosixFilePermission.OWNER_EXECUTE
                ));
            } catch (UnsupportedOperationException exception) {
                if (!executable.toFile().setExecutable(true)) {
                    throw new IOException("could not make fake engine executable");
                }
            }
        }
        return executable.getFileName().toString();
    }

    private static GradleRunner runner(Path project) {
        return runner(project, Map.of());
    }

    private static GradleRunner runner(Path project, Map<String, String> additions) {
        return GradleTestVersions.apply(GradleRunner.create()
            .withProjectDir(project.toFile())
            .withPluginClasspath()
            .withEnvironment(testEnvironment(project, additions))
            .withArguments(
                "--offline",
                "--build-cache",
                "--configuration-cache",
                "--parallel",
                "--stacktrace",
                "repostGenerate"
            ));
    }

    private static Map<String, String> testEnvironment(Path project, Map<String, String> additions) {
        Map<String, String> environment = new HashMap<>(System.getenv());
        environment.put("JAVA_HOME", System.getProperty("java.home"));
        environment.put("PATH", "/usr/bin:/bin");
        environment.putAll(additions);
        return environment;
    }

    private static void assertEngineFailure(
        Path project,
        String schema,
        String message,
        String span
    ) throws Exception {
        writeGeneratingProject(project, "");
        Files.writeString(project.resolve("repost/schema.repost"), schema + "\n");
        String output = runner(project).buildAndFail().getOutput();
        assertTrue(output.contains(message));
        if (span != null) {
            Path schemaFile = project.resolve("repost/schema.repost");
            String normalizedOutput = output.replace('\\', '/');
            String expected = schemaFile.toAbsolutePath().normalize().toString().replace('\\', '/');
            String canonical = schemaFile.toRealPath().toString().replace('\\', '/');
            assertTrue(
                normalizedOutput.contains(expected + ":" + span) ||
                    normalizedOutput.contains(canonical + ":" + span),
                output
            );
        }
    }

    private static String generatedText(Path project) throws IOException {
        StringBuilder text = new StringBuilder();
        Path generated = project.resolve("build");
        if (!Files.exists(generated)) {
            return "";
        }
        try (java.util.stream.Stream<Path> paths = Files.walk(generated)) {
            for (Path path : paths.filter(Files::isRegularFile)
                .collect(java.util.stream.Collectors.toList())) {
                text.append(Files.readString(path, StandardCharsets.UTF_8));
            }
        }
        return text.toString();
    }

    private static boolean containsNamed(Path root, String name) throws IOException {
        if (!Files.exists(root)) {
            return false;
        }
        try (java.util.stream.Stream<Path> paths = Files.walk(root)) {
            return paths.anyMatch(path -> path.getFileName().toString().equals(name));
        }
    }

    private static void writeRegistryProject(
        Path project,
        String registryId,
        String generatorId,
        String name
    ) throws IOException {
        Files.createDirectories(project);
        Files.writeString(project.resolve("build.gradle"), "plugins { id 'java' }\n");
        Path registry = project.resolve(
            "src/main/resources/META-INF/repost/registries/v1/" + registryId + "/registry.json"
        );
        Files.createDirectories(registry.getParent());
        Files.writeString(registry, registryJson(registryId, generatorId, name), StandardCharsets.UTF_8);
    }

    private static Path registryJar(
        Path path,
        String registryId,
        String generatorId,
        String name
    ) throws IOException {
        try (JarOutputStream output = new JarOutputStream(Files.newOutputStream(path))) {
            output.putNextEntry(new JarEntry(
                "META-INF/repost/registries/v1/" + registryId + "/registry.json"
            ));
            output.write(registryJson(registryId, generatorId, name).getBytes(StandardCharsets.UTF_8));
            output.closeEntry();
        }
        return path;
    }

    private static String registryJson(String registryId, String generatorId, String name) {
        String type = Character.toUpperCase(name.charAt(0)) + name.substring(1) + "Client";
        return "{\n" +
            "  \"formatVersion\": 1,\n" +
            "  \"registryId\": \"" + registryId + "\",\n" +
            "  \"registryType\": \"module\",\n" +
            "  \"clients\": [\n" +
            "    {\n" +
            "      \"formatVersion\": 1,\n" +
            "      \"generatorId\": \"" + generatorId + "\",\n" +
            "      \"language\": \"java\",\n" +
            "      \"packageName\": \"com.acme." + name + "\",\n" +
            "      \"clientType\": \"com.acme." + name + "." + type + "\",\n" +
            "      \"factoryType\": \"com.acme." + name + "." + type + "Factory\",\n" +
            "      \"schemaHash\": \"sha256:" + "a".repeat(64) + "\",\n" +
            "      \"descriptorVersion\": 2,\n" +
            "      \"runtimeVersion\": \"1.0.0\"\n" +
            "    }\n" +
            "  ]\n" +
            "}\n";
    }

    private static Path temporaryRoot(String name) throws IOException {
        Path base = Path.of(System.getenv().getOrDefault("REPOST_TEST_TMPDIR", System.getProperty("java.io.tmpdir")));
        return Files.createTempDirectory(base, "repost-gradle-" + name + "-").toAbsolutePath();
    }

    private static String shell(String value) {
        return "'" + value.replace("'", "'\\''") + "'";
    }

    private static void deleteTree(Path root) throws IOException {
        if (!Files.exists(root)) {
            return;
        }
        try (java.util.stream.Stream<Path> paths = Files.walk(root)) {
            for (Path path : paths.sorted(java.util.Comparator.reverseOrder())
                .collect(java.util.stream.Collectors.toList())) {
                Files.deleteIfExists(path);
            }
        }
    }
}
